services:

  bpmn_assistant:
    build:
      context: .
      dockerfile: ./src/bpmn_assistant/Dockerfile
    ports:
        - "8000:8000"
    networks:
      - bpmn-network

  bpmn_frontend:
    build:
      context: .
      dockerfile: ./src/bpmn_frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - bpmn_assistant
    networks:
        - bpmn-network

networks:
  bpmn-network:
    driver: bridge
